name: xgb
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - py-xgboost
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - librosa
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - pandas
  - shap
  - jupyter
  - scipy
  - transformers
  - pip:
    - spafe